config/routes.rb
Rails.application.routes.draw do
  resources :posts

  devise_for :users
  get 'static_pages/home'
  get 'static_pages/dash'
  get 'static_pages/dashtwo'
  
  get 'users/sign_up' => 'static_pages#dash'

  root 'static_pages#dash'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_one :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/controllers/static_pages_controller.rb
require 'nokogiri'
require 'open-uri'

class StaticPagesController < ApplicationController
  def home
  end
  
  def dash
    #new method - loops through H2's, looks for the @search_for variable (h2 on the destination page) and assigns CSS selector based on position.
    page = Nokogiri::HTML(open('http://www.ptv.vic.gov.au/live-travel-updates'))
    
    @posts = Post.all
    
    @mode_headings = page.xpath("//div/a/h2").collect {|node| node.text.strip}
    @search_for = "Additional information for Regional trains" #this is the string that we're searching for. Can be changed.
    @css_counter = 0 #offset by 1 to get true CSS position on page (Ruby starts from 0 rather than 1)
    
    
    @mode_headings.each do |mh|
      if mh == @search_for
        @css_position = @css_counter + 1
        @css_counter += 1
      else
        @css_counter += 1
      end
    end
    #these 2 CSS selectors pinpoint the position of the @search_for value above so it can be scraped.
    @vline_current_disruption = page.css(".article-grey-gradient:nth-child(#{@css_position}) .subGroup:nth-child(1) .disruptionArticleLink")
    @vline_upcoming_disruption = page.css(".article-grey-gradient:nth-child(#{@css_position}) .subGroup+ .subGroup .disruptionArticleLink")
    
    #OLD METHODS BE HERE
    #new method - counts H2's, subtracts 3 (to get to location of 'Regional Bus')
    # and then uses this to populate the CSS finder so it won't get out of whack.
    #regional bus will always be the third from the end, so can't see this breaking
    
    #@disruptions = page.css('h2').collect {|node| node.text.strip}
    #@page_h2_elements = page.xpath("//div/a/h2").collect {|node| node.text.strip}
    #@total_elements_count = @page_h2_elements.count
    #@regional_trains_location = @total_elements_count - 2
    #@vline_current_disruption = page.css(".article-grey-gradient:nth-child(#{@regional_trains_location}) .subGroup:nth-child(1) .disruptionArticleLink")
    #@vline_upcoming_disruption = page.css(".article-grey-gradient:nth-child(#{@regional_trains_location}) .subGroup+ .subGroup .disruptionArticleLink")
    
    #OLD METHOD FOR FINDING THE REGIONAL TRAINS CSS DIV NUMBERS
    
    #putting all variables in Static_Pages controller.
    #page = Nokogiri::HTML(open('http://www.ptv.vic.gov.au/live-travel-updates'))
    #Find all the H2 divs and strip the text out
    #@page_h2_elements = page.xpath("//div/a/h2").collect {|node| node.text.strip}
    #count the items in test_current to get the location of Regional Trains (starts from 0)
    #@regional_trains_location = @page_h2_elements.index("Additional information for Regional trains")
  
    #The CSS pointer changes if there's a 'General' alert on the site.
    #this code goes through the CSS, finds the 'Regional Trains' selector
    #and sets the CSS correctly so it doesn't get out of whack - the index
    #count starts from 0, so needs to be +1'd so it always finds the correct CSS

    
    # add 1 so that the CSS location matches up with the .index count 
    #@css_counter = @regional_trains_location + 1
    #change CSS selector with the css_counter injected in there so it's always accurate. 
    #@vline_current_disruption = page.css(".article-grey-gradient:nth-child(#{@css_counter}) .subGroup:nth-child(1) .disruptionArticleLink")
    #@vline_upcoming_disruption = page.css(".article-grey-gradient:nth-child(#{@css_counter}) .subGroup+ .subGroup .disruptionArticleLink")
  end
  
  def dashtwo
    #test dash
    #MAYBE if page contains general??@! we can then set the CSS selectore for upcoming / current disruptions accordingly.
    #testing various ways to get the best selector 
    page = Nokogiri::HTML(open('http://www.ptv.vic.gov.au/live-travel-updates'))
    #@details = @page.css('details').find{|node| node.css('h2').class == "articles-header Regional trains"}
    #@disruptions = page.css('h2/ul/li').collect {|node| node.text.strip}
    
    @disruptions = page.css('h2').collect {|node| node.text.strip}
    @page_h2_elements = page.xpath("//div/a/h2").collect {|node| node.text.strip}
    @total_elements_count = @page_h2_elements.count
    @regional_trains_location = @total_elements_count - 3
    @vline_current_disruption = page.css(".article-grey-gradient:nth-child(#{@regional_trains_location}) .subGroup:nth-child(1) .disruptionArticleLink")
    @vline_upcoming_disruption = page.css(".article-grey-gradient:nth-child(#{@regional_trains_location}) .subGroup+ .subGroup .disruptionArticleLink")
    
    
    
    #@disruptions = p page.xpath('//*[preceding-sibling::a][following-sibling::c]')
      
     # English: Starting at the root of the document: look in every div that has a class name containing the word 'product'. Inside that find a link. In that link find h4 text.

    #  XPath: //div[contains(@class,'product')]/a/h4
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("ptv.png", height:"20px"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-center">
        <li><a href=""><strong>Geelong Dash</strong></a></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href=""><strong>Updated at: </strong><%= DateTime.current.in_time_zone("Melbourne") %></a></li>        
      </ul>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PtvDash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<br>
<p><strong>
<%= link_to 'Create a New Post', new_post_path, :class => "btn btn-default btn-lg" %>
</p>
<br>
<br></strong>

<ul>
  <li>Delete items when they are no longer relevant.</li>
  <li>If there are no items, the 'Other Information' section will not display on the dash.</li>
  <li>Check the dash <%= link_to "HERE", root_path %> to see what the post looks like.</li>
</ul>
<p>
<%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "btn btn-default btn-lg" %>
</p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/_twitter_feed.html.erb
<a class="twitter-timeline" 
   data-chrome="noheader noscrollbar" 
   href="https://twitter.com/VLine" 
   data-widget-id="589654361480892416">Loading Tweets by @VLine</a>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/static_pages/dash.html.erb
<meta http-equiv="refresh" content="180" />

<div class="row">
  <div class="col-md-6">
    <h3>VLine Twitter Feed</h3>
      <%= render 'twitter_feed' %>
  </div>
  <div class="col-md-6" >
    <% if @vline_current_disruption.count > 0 %>
      <h3><%= @vline_current_disruption.count %> Current VLine Disruptions</h3>
        <ul>
            <% @vline_current_disruption.each do |p| %>
              <li>
                <h4><%= p.text %></h4>
              </li>
            <% end %>
        </ul>
    <% end %>    
    
    <% if @vline_upcoming_disruption.count > 0 %>
      <h3><%= @vline_upcoming_disruption.count %> Upcoming VLine Disruptions</h3>
        <ul>
            <% @vline_upcoming_disruption.each do |u| %>
              <li>
                <h4><%= u.text %></h4>
              </li>
          <% end %>
        </ul>
    <% end %>
    
    <% if @posts.count > 0 %>
    <h3>Other Information</h3>
      <ul>
        <% @posts.each do |p| %>
          <li>
            <h4><%= p.content %></h4>
          </li>
        <% end %>
      </ul>
    <% end %>
    
  </div>
</div>

app/views/static_pages/dashtwo.html.erb
THis is dash 2
<ul>
    <% @disruptions.each do |d| %>
        <li><%= d %></li>
    <% end %>
</ul>

<%= @total_elements_count %>
<%= @regional_trains_location %>

<% if @vline_current_disruption.count > 0 %>
      <h3><%= @vline_current_disruption.count %> Current VLine Disruptions</h3>
        <ul>
            <% @vline_current_disruption.each do |p| %>
              <li>
                <h4><%= p.text %></h4>
              </li>
            <% end %>
        </ul>
    <% end %>    
    
    <% if @vline_upcoming_disruption.count > 0 %>
      <h3><%= @vline_upcoming_disruption.count %> Upcoming VLine Disruptions</h3>
        <ul>
            <% @vline_upcoming_disruption.each do |u| %>
              <li>
                <h4><%= u.text %></h4>
              </li>
          <% end %>
        </ul>
    <% end %>

app/views/static_pages/home.html.erb
<% require 'nokogiri' %>
<% require 'open-uri' %>

<% page = Nokogiri::HTML(open('http://www.ptv.vic.gov.au/live-travel-updates')) %>
<% vline_disruption = page.css(".article-grey-gradient:nth-child(4) .disruptionArticleLink") %>
<% mode = page.css(".article-grey-gradient:nth-child(4)").text %>
<%= mode %>


<h1> Test Dash </h1>

<h1>Non Loop</h1>

<%= page.at_css("li").text %>

<h1>Loop</h1>

<table>

  <% vline_disruption.each do |p| %>
<tr><td>
<%= p.text %>
  </tr></td>
<% end %>